"""
importer.py — Import tasks from CSV, TXT, or PDF
=================================================
Each function returns a list of dicts with keys:
  name, description, category, priority, due_date (str or ""), done (bool)

The caller is responsible for converting to Task objects.
PDF import requires pdfplumber (pip install pdfplumber).
"""
import csv
import re
from datetime import datetime


# ── helpers ───────────────────────────────────────────────────────────────────

def _parse_date(s: str):
    """Try several date formats; return datetime.date or None."""
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y", "%d %b %Y", "%d %B %Y"):
        try:
            return datetime.strptime(s.strip(), fmt).date()
        except ValueError:
            pass
    return None


def _clean(s: str) -> str:
    return s.strip() if s else ""


VALID_PRIORITIES = {"High", "Medium", "Low"}
VALID_CATEGORIES = None   # None means accept anything


def _coerce_priority(raw: str) -> str:
    raw = raw.strip().capitalize()
    return raw if raw in VALID_PRIORITIES else "Medium"


# ── CSV ───────────────────────────────────────────────────────────────────────

def import_csv(path: str) -> list[dict]:
    """
    Import from a CSV file.
    Accepts the app's own export format AND generic CSVs.
    Required column: Name (or Task, Title, Task Name).
    Optional columns: Description, Category, Priority, Due Date, Done.
    Column matching is case-insensitive.
    """
    results = []
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            return results

        # Build case-insensitive field map
        field_map = {h.strip().lower(): h for h in reader.fieldnames}

        def get_field(row, *candidates):
            for c in candidates:
                key = field_map.get(c.lower())
                if key and key in row:
                    return _clean(row[key])
            return ""

        for row in reader:
            name = get_field(row, "name", "task name", "task", "title")
            if not name:
                continue
            done_raw = get_field(row, "done", "completed", "status").lower()
            done = done_raw in ("yes", "true", "1", "done", "complete", "completed")
            results.append({
                "name":        name,
                "description": get_field(row, "description", "desc", "notes", "note"),
                "category":    get_field(row, "category", "cat", "group", "tag") or "General",
                "priority":    _coerce_priority(get_field(row, "priority", "importance")),
                "due_date":    _parse_date(get_field(row, "due date", "due", "deadline", "date")),
                "done":        done,
            })
    return results


# ── TXT ───────────────────────────────────────────────────────────────────────

def import_txt(path: str) -> list[dict]:
    """
    Import from a plain-text file.
    Understands the app's own TXT export format, plus simple one-task-per-line lists.

    App export format recognised lines:
      [  CATEGORY  ]          → current category context
      ○ / ✓ icon name ...     → task line
          description text    → optional description (indented)
      Due: YYYY-MM-DD         → embedded in task line

    Fallback: any non-blank, non-header line becomes a task named after itself.
    """
    results   = []
    current_cat = "General"
    pending     = None   # last task dict waiting for a description line

    with open(path, encoding="utf-8") as f:
        lines = f.readlines()

    def flush(task):
        if task:
            results.append(task)

    for raw in lines:
        line = raw.rstrip()

        # ── category header ──────────────────────────────
        cat_match = re.match(r"^\[\s*([A-Z][A-Z\s]+)\s*\]$", line)
        if cat_match:
            flush(pending); pending = None
            current_cat = cat_match.group(1).strip().title()
            continue

        # ── horizontal rules / headers ───────────────────
        if re.match(r"^[=\-]{5,}$", line) or re.match(r"^MY TASKS$", line, re.I):
            flush(pending); pending = None
            continue

        # skip blank lines and export metadata lines
        if not line.strip():
            flush(pending); pending = None
            continue
        if re.match(r"^(Exported:|Total:|Generated by)", line.strip()):
            continue

        # ── task line (starts with ○, ✓, -, *, •, numbers) ──
        task_match = re.match(
            r"^\s*([○✓✔\-\*•]|\d+[\.\)])\s+"
            r"(?:([🔥⚡🌿])\s+)?"       # optional priority icon
            r"(.+?)(?:\s+Due:\s*(\S+))?$",
            line
        )
        if task_match:
            flush(pending)
            done_marker = task_match.group(1) in ("✓", "✔")
            pri_icon    = task_match.group(2) or ""
            name_rest   = task_match.group(3).strip()
            due_str     = task_match.group(4) or ""

            pri_map = {"🔥": "High", "⚡": "Medium", "🌿": "Low"}
            priority = pri_map.get(pri_icon, "Medium")

            pending = {
                "name":        name_rest,
                "description": "",
                "category":    current_cat,
                "priority":    priority,
                "due_date":    _parse_date(due_str),
                "done":        done_marker,
            }
            continue

        # ── indented description continuation ────────────
        if pending and raw.startswith("    ") and line.strip():
            if not pending["description"]:
                pending["description"] = line.strip()
            else:
                pending["description"] += " " + line.strip()
            continue

        # ── fallback: plain line becomes a task name ─────
        text = line.strip()
        if len(text) > 2:
            flush(pending)
            pending = {
                "name":        text,
                "description": "",
                "category":    current_cat,
                "priority":    "Medium",
                "due_date":    None,
                "done":        False,
            }

    flush(pending)
    return results


# ── PDF ───────────────────────────────────────────────────────────────────────

def import_pdf(path: str) -> list[dict]:
    """
    Import from a PDF file.
    Extracts all text then runs the same parser as import_txt.
    Works best with the app's own PDF export, but will attempt any text PDF.
    Requires: pip install pdfplumber
    """
    try:
        import pdfplumber  # type: ignore
    except ImportError:
        raise ImportError(
            "pdfplumber is required for PDF import.\n"
            "Install it with:  pip install pdfplumber"
        )

    lines = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            text = page.extract_text(x_tolerance=2, y_tolerance=2)
            if text:
                lines.extend(text.splitlines())

    # Write to a temporary string buffer and reuse the TXT parser logic
    import tempfile, os
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt",
                                     encoding="utf-8", delete=False) as tmp:
        tmp.write("\n".join(lines))
        tmp_path = tmp.name
    try:
        return import_txt(tmp_path)
    finally:
        os.unlink(tmp_path)